name: Build PHP 7.x Image

on:
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP 7.x Version'
        default: '7.2.34'
        required: true
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build PHP-7.x and Push
        uses: docker/build-push-action@v5
        with:
          context: php/${{ github.event.inputs.php_version }}
          file: php/${{ github.event.inputs.php_version }}/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: |
            corapanel/php:${{ github.event.inputs.php_version }}-fpm
          cache-from: type=gha
          cache-to: type=gha,mode=max