name: Build PHP 7 Image

on:
  workflow_dispatch:
    inputs:
      php74Version:
        description: 'PHP 7.4 Version'
        default: '7.4.33'
        required: true
      php73Version:
        description: 'PHP 7.3 Version'
        default: '7.3.33'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build PHP-7.4 and Push
        uses: docker/build-push-action@v5
        with:
          context: php/7
          file: php/7/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/s390x
          push: true
          build-args:
            PHP_VERSION=${{ github.event.inputs.php74Version }}
          tags: |
            corapanel/php:${{ github.event.inputs.php74Version }}-fpm
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build PHP-7.3 and Push
        uses: docker/build-push-action@v5
        with:
          context: php/7
          file: php/7/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/s390x
          push: true
          build-args:
            PHP_VERSION=${{ github.event.inputs.php73Version }}
          tags: |
            corapanel/php:${{ github.event.inputs.php73Version }}-fpm
          cache-from: type=gha
          cache-to: type=gha,mode=max
